name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - "1.85" # Current MSRV due to Cargo MSRV feature
          - stable
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/rust-build
        with:
          toolchain: ${{ matrix.toolchain }}


