name: Build (decoder)
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: decoder
      - name: Build
        working-directory: decoder
        shell: bash
        run: cargo build --all-features --verbose
      - name: Run tests
        working-directory: decoder
        shell: bash
        run: cargo test --all-features --verbose
