name: Formatting and Linting
on: [pull_request]

jobs:
  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run fmt check
        id: cargoFmt
        shell: bash
        run: cargo fmt --all -- --check
      - name: Run fmt check - decoder
        id: cargoFmtDecoder
        shell: bash
        working-directory: decoder
        run: cargo fmt --all -- --check
  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy check
        id: cargoClippy
        shell: bash
        run: cargo clippy --workspace --all-features -- -D warnings
  clippyDecoder:
    name: Cargo clippy (decoder)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: decoder
      - name: Run clippy check - decoder
        id: cargoClippyDecoder
        shell: bash
        working-directory: decoder
        run: cargo clippy --workspace --all-features -- -D warnings
